HELP_COMMANDS = {
    "me": "Info about yourself",
    "buy": "!buy COMMAND or !buy random - Buy a Command with Cool Points",
    "love": "!love USER COMMAND - Show support for a command (Unmutes if theres Haters)",
    "hate": "!hate USER COMMAND - Vote to silence a command",
    "steal": "!steal COMMAND USER - steal a command from someone elses, cost Cool Points",
    "share": "!share COMMAND USER - share access to a command",
    "transfer": "!transfer COMMAND USER - transfer command to someone, costs no cool points",
    "props": "!props @beginbot (AMOUNT_OF_STREET_CRED) - Give you street cred to beginbot",
    "perms": "!perms !clap OR !perms @beginbot - See who is allowed to use the !clap command",
    "donate": "!donate give away all your commands to random users",
    "issue": "!issue Description of a Bug - A bug you found you want Beginbot to look at",
    "coup": "trigger either a revolution or a crushing or the rebellion based on !vote - if you don't have enough Cool Points to afford to trigger a coup, you will be stripped of all your Street Cred and Cool Points",
    "soundeffect": "!soundeffect YOUTUBE_URL COMMAND_NAME 00:01 00:05 - Must be less than 5 second",
    "vote": "!vote (peace|revolution) - Where you stand when a coup happens.  Should all sounds be redistributed, or should the trouble makes lose their sounds and the rich get richer",
}
